package dev.blynchik.magicRangers.config;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import dev.blynchik.magicRangers.model.storage.AnimalName;
import dev.blynchik.magicRangers.model.storage.ColorName;
import org.springframework.context.MessageSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.support.ResourceBundleMessageSource;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

@Configuration
public class AppConfig {

    @Bean
    public MessageSource messageSource() {
        ResourceBundleMessageSource messageSource = new ResourceBundleMessageSource();
        messageSource.setBasenames("messages");
        messageSource.setDefaultEncoding("UTF-8");
        return messageSource;
    }

    @Bean
    public ObjectMapper objectMapper() {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        objectMapper.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        return objectMapper;
    }

    @Bean
    public List<AnimalName> animalName() {
        return List.of(new AnimalName("кот", 1), new AnimalName("собака", 2), new AnimalName("осел", 1), new AnimalName("козел", 1), new AnimalName("лошадь", 2), new AnimalName("свинья", 2), new AnimalName("кролик", 1), new AnimalName("трубкозуб", 1), new AnimalName("альбатрос", 1), new AnimalName("аллигатор", 1), new AnimalName("альпака", 2), new AnimalName("амфибия", 2), new AnimalName("анаконда", 2), new AnimalName("удильщик", 1), new AnimalName("муравей", 1), new AnimalName("муравьед", 1), new AnimalName("антилопа", 2), new AnimalName("обезьяна", 2), new AnimalName("тля", 2), new AnimalName("жерех", 1), new AnimalName("бабуин", 1), new AnimalName("барсук", 1), new AnimalName("бандикут", 1), new AnimalName("ракушка", 2), new AnimalName("барракуда", 2), new AnimalName("василиск", 1), new AnimalName("бас", 1), new AnimalName("бобр", 1), new AnimalName("клоп", 1), new AnimalName("пчела", 2), new AnimalName("жук", 1), new AnimalName("птица", 2), new AnimalName("бизон", 1), new AnimalName("удав", 1), new AnimalName("кабан", 1), new AnimalName("рысь", 2), new AnimalName("бонобо", 1), new AnimalName("мина", 2), new AnimalName("бовид", 1), new AnimalName("бабочка", 2), new AnimalName("канюк", 1), new AnimalName("верблюд", 1), new AnimalName("водосвинка", 2), new AnimalName("кардинал", 1), new AnimalName("карибу", 1), new AnimalName("карп", 1), new AnimalName("гусеница", 2), new AnimalName("сом", 1), new AnimalName("сороконожка", 2), new AnimalName("моллюск", 1), new AnimalName("хамелеон", 1), new AnimalName("гепард", 1), new AnimalName("синица", 2), new AnimalName("курица", 2), new AnimalName("шимпанзе", 1), new AnimalName("шиншилла", 2), new AnimalName("бурундук", 1), new AnimalName("кобра", 2), new AnimalName("таракан", 1), new AnimalName("треска", 2), new AnimalName("кондор", 1), new AnimalName("констриктор", 1), new AnimalName("пума", 2), new AnimalName("корова", 2), new AnimalName("койот", 1), new AnimalName("краб", 1), new AnimalName("кран", 1), new AnimalName("рак", 1), new AnimalName("крикет", 1), new AnimalName("крокодил", 1), new AnimalName("ворона", 2), new AnimalName("кукушка", 2), new AnimalName("цикада", 2), new AnimalName("олень", 1), new AnimalName("динго", 1), new AnimalName("динозавр", 1), new AnimalName("дельфин", 1), new AnimalName("соня", 2), new AnimalName("голубь", 1), new AnimalName("стрекоза", 2), new AnimalName("дракон", 1), new AnimalName("утка", 2), new AnimalName("орел", 1), new AnimalName("червь", 1), new AnimalName("уховертка", 2), new AnimalName("ехидна", 2), new AnimalName("угорь", 1), new AnimalName("цапля", 2), new AnimalName("слон", 1), new AnimalName("лось", 1), new AnimalName("эму", 1), new AnimalName("горностай", 1), new AnimalName("сокол", 1), new AnimalName("хорек", 1), new AnimalName("зяблик", 1), new AnimalName("светляк", 1), new AnimalName("фламинго", 1), new AnimalName("блоха", 2), new AnimalName("лиса", 2), new AnimalName("лягушка", 2), new AnimalName("газель", 2), new AnimalName("геккон", 1), new AnimalName("песчанка", 2), new AnimalName("гиббон", 1), new AnimalName("жираф", 1), new AnimalName("гусь", 1), new AnimalName("суслик", 1), new AnimalName("горилла", 2), new AnimalName("кузнечик", 1), new AnimalName("рябчик", 1), new AnimalName("гуань", 1), new AnimalName("гуанако", 1), new AnimalName("цесарка", 2), new AnimalName("чайка", 2), new AnimalName("гуппи", 2), new AnimalName("пикша", 2), new AnimalName("палтус", 1), new AnimalName("хомяк", 1), new AnimalName("заяц", 1), new AnimalName("лунь", 1), new AnimalName("ястреб", 1), new AnimalName("ежик", 1), new AnimalName("сельдь", 2), new AnimalName("бегемот", 1), new AnimalName("анкилостома", 2), new AnimalName("шершень", 1), new AnimalName("журчалка", 2), new AnimalName("колибри", 1), new AnimalName("игуана", 2), new AnimalName("импала", 2), new AnimalName("шакал", 1), new AnimalName("ягуар", 1), new AnimalName("медуза", 2), new AnimalName("кенгуру", 1), new AnimalName("зимородок", 1), new AnimalName("змей", 1), new AnimalName("киви", 1), new AnimalName("коала", 2), new AnimalName("кои", 1), new AnimalName("криль", 2), new AnimalName("минога", 2), new AnimalName("жаворонок", 1), new AnimalName("пиявка", 1), new AnimalName("лемминг", 1), new AnimalName("лемур", 1), new AnimalName("леопард", 1), new AnimalName("леопон", 1), new AnimalName("лимпет", 1), new AnimalName("лев", 1), new AnimalName("ящерица", 2), new AnimalName("лама", 2), new AnimalName("омар", 1), new AnimalName("саранча", 2), new AnimalName("гагара", 2), new AnimalName("вошь", 2), new AnimalName("ара", 1), new AnimalName("скумбрия", 2), new AnimalName("сорока", 2), new AnimalName("ламантин", 1), new AnimalName("мандрил", 1), new AnimalName("марлин", 1), new AnimalName("мартышка", 2), new AnimalName("сурок", 1), new AnimalName("куница", 2), new AnimalName("мастодонт", 1), new AnimalName("медоуларк", 1), new AnimalName("сурикат", 1), new AnimalName("норка", 2), new AnimalName("пескарь", 1), new AnimalName("клещ", 1), new AnimalName("пересмешник", 1), new AnimalName("моль", 2), new AnimalName("мангуст", 1), new AnimalName("комар", 1), new AnimalName("мышь", 2), new AnimalName("мул", 1), new AnimalName("овцебык", 1), new AnimalName("нарвал", 1), new AnimalName("тритон", 1), new AnimalName("соловей", 1), new AnimalName("оцелот", 1), new AnimalName("осьминог", 1), new AnimalName("опоссум", 1), new AnimalName("орангутанг", 1), new AnimalName("страус", 1), new AnimalName("выдра", 2), new AnimalName("сова", 2), new AnimalName("бык", 1), new AnimalName("панда", 2), new AnimalName("пантера", 2), new AnimalName("попугай", 1), new AnimalName("куропатка", 2), new AnimalName("павлин", 1), new AnimalName("пеликан", 1), new AnimalName("пингвин", 1), new AnimalName("окунь", 1), new AnimalName("фазан", 1), new AnimalName("щука", 2), new AnimalName("пиранья", 2), new AnimalName("планарий", 1), new AnimalName("утконос", 1), new AnimalName("пони", 1), new AnimalName("дикобраз", 1), new AnimalName("креветка", 2), new AnimalName("примас", 1), new AnimalName("тупик", 1), new AnimalName("питон", 1), new AnimalName("перепел", 1), new AnimalName("енот", 1), new AnimalName("крыса", 2), new AnimalName("змея", 2), new AnimalName("ворон", 1), new AnimalName("рептилия", 2), new AnimalName("носорог", 1), new AnimalName("грызун", 1), new AnimalName("ладья", 2), new AnimalName("петух", 1), new AnimalName("аскарид", 1), new AnimalName("парусник", 1), new AnimalName("саламандра", 2), new AnimalName("лосось", 1), new AnimalName("гребешок", 1), new AnimalName("скорпион", 1), new AnimalName("акула", 2), new AnimalName("овцa", 2), new AnimalName("землеройка", 2), new AnimalName("шелкопряд", 1), new AnimalName("сцинк", 1), new AnimalName("скунс", 1), new AnimalName("слизняк", 1), new AnimalName("корюшка", 2), new AnimalName("улитка", 2), new AnimalName("бекас", 1), new AnimalName("воробей", 1), new AnimalName("паук", 1), new AnimalName("колпица", 2), new AnimalName("кальмар", 1), new AnimalName("белка", 2), new AnimalName("скат", 1), new AnimalName("аист", 1), new AnimalName("осетр", 1), new AnimalName("ласточка", 2), new AnimalName("лебедь", 1), new AnimalName("тар", 1), new AnimalName("такин", 1), new AnimalName("тарантул", 1), new AnimalName("долгопят", 1), new AnimalName("термит", 1), new AnimalName("крачка", 2), new AnimalName("дрозд", 1), new AnimalName("тигр", 1), new AnimalName("тиглон", 1), new AnimalName("жаба", 2), new AnimalName("черепаха", 2), new AnimalName("тукан", 1), new AnimalName("форель", 1), new AnimalName("тунец", 1), new AnimalName("индюк", 1), new AnimalName("тиранозавр", 1), new AnimalName("уриал", 1), new AnimalName("викунья", 2), new AnimalName("гадюка", 2), new AnimalName("полевка", 2), new AnimalName("гриф", 1), new AnimalName("валлаби", 1), new AnimalName("морж", 1), new AnimalName("оса", 2), new AnimalName("ласка", 2), new AnimalName("кит", 1), new AnimalName("сиг", 1), new AnimalName("дичь", 2), new AnimalName("волк", 1), new AnimalName("росомаха", 2), new AnimalName("вомбат", 1), new AnimalName("дятел", 1), new AnimalName("крапивник", 1), new AnimalName("як", 1), new AnimalName("зебра", 2), new AnimalName("гаял", 1));
    }

    @Bean
    public List<ColorName> colorName() {
        List<ColorName> colors = new ArrayList<>();
        String male1 = "ый";
        String male2 = "ий";
        String male3 = "ой";
        String female1 = "ая";
        String female2 = "яя";
        String mid1 = "ое";
        String mid2 = "ee";
        colors.add(new ColorName("Абрикосов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Агатов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Аквамаринов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ализаринов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ал", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Амарантов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Аметистов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Антрацитов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Баклажанов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бежев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бел", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бирюзов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бисквитн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Блошин", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бобров", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Болотн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бордов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бриллиантов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бронзов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Бур", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ванильн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Васильков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Вердепешев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Вердепомов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Вишнев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Гелиотропов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Глинян", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Глубок", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Голуб", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Горн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Горчичн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Гранатов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Гранитн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Графитов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Гридеперлев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Грушев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Джазов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Джинсов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Дик", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Долларов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Елов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Жевательн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Желт", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Жжен", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Защитн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Зелен", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Золот", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Известков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Изумрудн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Июньск", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Кадетск", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Камелопардов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Канареечн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Карамельн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Каштанов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Кварцев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Кирпичн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Кленов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Кобальтов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Кораллов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Коричнев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Коричн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Королевск", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Космическ", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Кофейн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Красн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Кремов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Кричащ", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Крут", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Кукурузн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лавандов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лазерн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лазурн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Латунн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лесн", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Ливерн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лилов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лимонн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лиственн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Лососев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Льнян", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Люминесцентн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Магическ", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Маисов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Майск", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Малахитов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Малинов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Мандаринов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Медн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Медов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Международн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Мертвенн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Миртов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Модн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Мокасинов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Мокр", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Морковн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Морозн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Морск", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Мятн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Насыщенн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Натуральн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Небесн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Незрел", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Нефритов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ночн", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Обычн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Огненн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Одуванчиков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Океанск", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Оливков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Опалов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Оперн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Оранжев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Отборн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Охотнич", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Очищенн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пепельн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Перламутров", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Персиков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Песочн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пигментн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пихтов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пламенн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Платинов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Полуночн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Последн", new String[]{male2, female2, mid2}));
        colors.add(new ColorName("Призрачн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пурпурн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пшеничн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пылк", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пыльн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Пюсов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Радикальн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Рапсов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Резедов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ржав", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Розоват", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Розов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Рубинов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Рус", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Рыж", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Салатов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сапфиров", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Светл", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сер", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Серебрист", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Серебрян", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Серобуромалинов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сероват", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сер", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сигнальн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сиз", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Синеват", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Син", new String[]{male2, female2, mid2}));
        colors.add(new ColorName("Сиренев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сияющ", new String[]{male2, female2, mid2}));
        colors.add(new ColorName("Скандальн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сладк", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Сланцев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сливов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сливочн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Слонов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Снежн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Солнечн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Соснов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Средн", new String[]{male2, female2, mid2}));
        colors.add(new ColorName("Стальн", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Старинн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Стар", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Сырн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Темн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Терракотов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Тихоокеанск", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Тицианов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Томатн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Травян", new String[]{male3, female1, mid1}));
        colors.add(new ColorName("Транспортн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Тростников", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Тускл", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Тыквенн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ультрамаринов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Умеренн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Фиалков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Фиолетов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Фисташков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Фталев", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Фталоцианинов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Хромов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Цветочн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Цементн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Цинков", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Черн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Шафранов", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Шокирующ", new String[]{male2, female1, mid1}));
        colors.add(new ColorName("Шоколадн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Экстравагантн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ядовит", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Янтарн", new String[]{male1, female1, mid1}));
        colors.add(new ColorName("Ярк", new String[]{male2, female1, mid1}));
        return Collections.unmodifiableList(colors);
    }
}
